// Default question database for Ban Co Dam Choi.
// Add or edit questions here; gameplay logic lives in script.js.
(function () {
    window.DEFAULT_QUESTION_BANK = {
        truth: [
            { id: "truth_001", text: "Trong nhóm này, ai làm bạn cười nhiều nhất?", type: "truth", difficulty: "easy", rarity: "common" },
            { id: "truth_002", text: "Ai trong nhóm có năng lượng giống trưởng nhóm nhất?", type: "truth", difficulty: "easy", rarity: "common" },
            { id: "truth_003", text: "Nếu phải lập team 3 người để đi chơi xa, bạn chọn ai?", type: "truth", difficulty: "easy", rarity: "common" },
            { id: "truth_004", text: "Bạn thấy ai trong nhóm dễ thân nhất?", type: "truth", difficulty: "easy", rarity: "common" },
            { id: "truth_005", text: "Ai trong nhóm có gu ăn mặc hợp mắt bạn nhất?", type: "truth", difficulty: "easy", rarity: "common" },
            { id: "truth_006", text: "Bạn nghĩ ai là người hay cứu nguy không khí im lặng nhất?", type: "truth", difficulty: "easy", rarity: "common" },
            { id: "truth_007", text: "Nếu cả nhóm đi thi gameshow, bạn muốn ai làm đội trưởng?", type: "truth", difficulty: "easy", rarity: "common" },
            { id: "truth_008", text: "Bạn từng nói dối điều gì nhỏ gần đây nhất?", type: "truth", difficulty: "easy", rarity: "common" },
            { id: "truth_009", text: "Tật xấu dễ bị phát hiện nhất của bạn là gì?", type: "truth", difficulty: "easy", rarity: "common" },
            { id: "truth_010", text: "Ai trong nhóm nhìn có vẻ bí ẩn nhất?", type: "truth", difficulty: "easy", rarity: "common" },
            { id: "truth_011", text: "Nếu đổi chỗ ngồi với một người trong nhóm, bạn chọn ai?", type: "truth", difficulty: "easy", rarity: "common" },
            { id: "truth_012", text: "Bạn nghĩ ai trong nhóm hợp làm MC nhất?", type: "truth", difficulty: "easy", rarity: "common" },
            { id: "truth_013", text: "Ấn tượng đầu tiên của bạn về người bên trái là gì?", type: "truth", difficulty: "medium", rarity: "common" },
            { id: "truth_014", text: "Ấn tượng đầu tiên của bạn về người bên phải là gì?", type: "truth", difficulty: "medium", rarity: "common" },
            { id: "truth_015", text: "Bạn từng giả vờ bận để né ai chưa?", type: "truth", difficulty: "medium", rarity: "common" },
            { id: "truth_016", text: "Nếu phải đổi tính cách với một người trong nhóm, bạn chọn ai?", type: "truth", difficulty: "medium", rarity: "rare" },
            { id: "truth_017", text: "Ai trong nhóm khiến bạn muốn nói chuyện nhiều hơn?", type: "truth", difficulty: "medium", rarity: "rare" },
            { id: "truth_018", text: "Bạn nghĩ ai trong nhóm dễ bị dụ đi ăn khuya nhất?", type: "truth", difficulty: "medium", rarity: "common" },
            { id: "truth_019", text: "Ai trong nhóm có vẻ giữ bí mật tốt nhất?", type: "truth", difficulty: "medium", rarity: "common" },
            { id: "truth_020", text: "Ai trong nhóm hay tạo cảm giác đáng tin nhất?", type: "truth", difficulty: "medium", rarity: "rare" },
            { id: "truth_021", text: "Bạn từng hiểu lầm ai trong nhóm chưa?", type: "truth", difficulty: "medium", rarity: "rare" },
            { id: "truth_022", text: "Nếu được chọn một người trong nhóm làm cố vấn tình cảm, bạn chọn ai?", type: "truth", difficulty: "medium", rarity: "rare" },
            { id: "truth_023", text: "Bạn nghĩ ai trong nhóm dễ nổi tiếng trên mạng nhất?", type: "truth", difficulty: "medium", rarity: "common" },
            { id: "truth_024", text: "Có thói quen nào của bạn mà bạn sợ người khác phát hiện?", type: "truth", difficulty: "medium", rarity: "rare" },
            { id: "truth_025", text: "Nếu cả nhóm phải sống chung 1 tuần, ai sẽ là người khó ở chung nhất?", type: "truth", difficulty: "hard", rarity: "rare" },
            { id: "truth_026", text: "Bạn từng thích thầm ai mà không ai biết chưa?", type: "truth", difficulty: "hard", rarity: "epic" },
            { id: "truth_027", text: "Có chuyện gì bạn từng làm mà đến giờ vẫn hơi xấu hổ?", type: "truth", difficulty: "hard", rarity: "rare" },
            { id: "truth_028", text: "Ai trong nhóm bạn từng đánh giá sai nhất?", type: "truth", difficulty: "hard", rarity: "epic" },
            { id: "truth_029", text: "Nếu phải nói một lời thật lòng với người đối diện, bạn sẽ nói gì?", type: "truth", difficulty: "hard", rarity: "epic" },
            { id: "truth_030", text: "Bạn từng ghen tị với ai trong nhóm chưa? Vì sao?", type: "truth", difficulty: "hard", rarity: "epic" },
            { id: "truth_031", text: "Tin nhắn nào trong điện thoại bạn không muốn bị đọc nhất?", type: "truth", difficulty: "hard", rarity: "epic" },
            { id: "truth_032", text: "Bạn từng né một cuộc hẹn vì lý do không thật chưa?", type: "truth", difficulty: "hard", rarity: "rare" },
            { id: "truth_033", text: "Ai trong nhóm làm bạn bất ngờ nhất sau khi quen lâu hơn?", type: "truth", difficulty: "hard", rarity: "rare" },
            { id: "truth_034", text: "Nếu được hỏi một câu thật lòng với bất kỳ ai ở đây, bạn muốn hỏi ai và hỏi gì?", type: "truth", difficulty: "insane", rarity: "epic" },
            { id: "truth_035", text: "Một bí mật nhẹ nếu nói ra sẽ làm cả nhóm bất ngờ là gì?", type: "truth", difficulty: "insane", rarity: "legendary" },
            { id: "truth_036", text: "Bạn từng có cảm giác không hợp với ai trong nhóm lúc đầu chưa?", type: "truth", difficulty: "insane", rarity: "legendary" },
            { id: "truth_037", text: "Nếu phải chọn một người trong nhóm để đi du lịch riêng 2 ngày, bạn chọn ai?", type: "truth", difficulty: "insane", rarity: "legendary" },
            { id: "truth_038", text: "Bạn đang giấu cảm xúc gì mà người khác ít nhận ra?", type: "truth", difficulty: "insane", rarity: "legendary" },
            { id: "truth_039", text: "Nếu được tua lại một khoảnh khắc trong nhóm này, bạn muốn sửa điều gì?", type: "truth", difficulty: "insane", rarity: "legendary" },
            { id: "truth_040", text: "Ai trong nhóm khiến bạn tò mò nhất nhưng chưa dám hỏi nhiều?", type: "truth", difficulty: "insane", rarity: "legendary" }
        ],
        dare: [
            { id: "dare_001", text: "Hát 10 giây một bài thiếu nhi.", type: "dare", difficulty: "easy", rarity: "common" },
            { id: "dare_002", text: "Tạo một dáng pose thật tự tin trong 5 giây.", type: "dare", difficulty: "easy", rarity: "common" },
            { id: "dare_003", text: "Nói một câu khen người bên phải thật nghiêm túc.", type: "dare", difficulty: "easy", rarity: "common" },
            { id: "dare_004", text: "Nói một câu khen người bên trái thật cụ thể.", type: "dare", difficulty: "easy", rarity: "common" },
            { id: "dare_005", text: "Bắt tay 3 người gần bạn nhất như đang ký hợp đồng lớn.", type: "dare", difficulty: "easy", rarity: "common" },
            { id: "dare_006", text: "Chọn 2 người làm nền và tạo một bức ảnh pose trong 5 giây.", type: "dare", difficulty: "easy", rarity: "common" },
            { id: "dare_007", text: "Nói tên 5 người trong nhóm trong vòng 5 giây.", type: "dare", difficulty: "easy", rarity: "common" },
            { id: "dare_008", text: "Đổi chỗ với người xa bạn nhất.", type: "dare", difficulty: "easy", rarity: "common" },
            { id: "dare_009", text: "Làm mặt nghiêm túc trong 10 giây trong khi cả nhóm nhìn bạn.", type: "dare", difficulty: "easy", rarity: "common" },
            { id: "dare_010", text: "Chọn một người và high-five thật hoành tráng.", type: "dare", difficulty: "easy", rarity: "common" },
            { id: "dare_011", text: "Đọc một câu thoại phim như đang nhận giải Oscar.", type: "dare", difficulty: "medium", rarity: "common" },
            { id: "dare_012", text: "Nhảy lò cò một vòng quanh nhóm.", type: "dare", difficulty: "medium", rarity: "common" },
            { id: "dare_013", text: "Để nhóm chọn một biệt danh cho bạn trong 2 lượt.", type: "dare", difficulty: "medium", rarity: "rare" },
            { id: "dare_014", text: "Diễn lại biểu cảm của người đang rất đói trong 10 giây.", type: "dare", difficulty: "medium", rarity: "common" },
            { id: "dare_015", text: "Chọn 3 người và tạo một slogan cho team đó.", type: "dare", difficulty: "medium", rarity: "rare" },
            { id: "dare_016", text: "Làm hướng dẫn viên giới thiệu căn phòng này trong 20 giây.", type: "dare", difficulty: "medium", rarity: "common" },
            { id: "dare_017", text: "Bắt chước dáng đi của một nhân vật nổi tiếng trong 10 giây.", type: "dare", difficulty: "medium", rarity: "rare" },
            { id: "dare_018", text: "Chỉ dùng 3 từ để mô tả người đối diện.", type: "dare", difficulty: "medium", rarity: "common" },
            { id: "dare_019", text: "Cả nhóm đếm ngược từ 10, bạn phải tạo dáng khác nhau mỗi 2 số.", type: "dare", difficulty: "medium", rarity: "rare" },
            { id: "dare_020", text: "Nói một câu quảng cáo cho chính mình trong 15 giây.", type: "dare", difficulty: "medium", rarity: "rare" },
            { id: "dare_021", text: "Mời một người trong nhóm làm giám khảo và biểu diễn 10 giây.", type: "dare", difficulty: "medium", rarity: "rare" },
            { id: "dare_022", text: "Đặt tên nhóm nhạc cho 4 người gần bạn nhất.", type: "dare", difficulty: "medium", rarity: "common" },
            { id: "dare_023", text: "Diễn một cảnh phim câm 15 giây để nhóm đoán cảm xúc.", type: "dare", difficulty: "hard", rarity: "rare" },
            { id: "dare_024", text: "Để người bên trái điều khiển bạn như robot trong 20 giây.", type: "dare", difficulty: "hard", rarity: "epic" },
            { id: "dare_025", text: "Gọi điện hoặc nhắn tin cho một người quen và nói một câu tích cực.", type: "dare", difficulty: "hard", rarity: "rare" },
            { id: "dare_026", text: "Rap ngẫu hứng 20 giây về người vừa quay trúng.", type: "dare", difficulty: "hard", rarity: "epic" },
            { id: "dare_027", text: "Để nhóm chọn một câu cửa miệng, bạn phải nói câu đó trong 2 lượt.", type: "dare", difficulty: "hard", rarity: "epic" },
            { id: "dare_028", text: "Tạo một màn chào sân cho người bên phải như siêu sao.", type: "dare", difficulty: "hard", rarity: "rare" },
            { id: "dare_029", text: "Chọn 2 người làm đồng đội và diễn một quảng cáo 20 giây.", type: "dare", difficulty: "hard", rarity: "epic" },
            { id: "dare_030", text: "Để cả nhóm chọn một từ cấm, bạn không được nói từ đó trong 3 lượt.", type: "dare", difficulty: "hard", rarity: "epic" },
            { id: "dare_031", text: "Đăng một story tự dìm nhẹ trong 5 phút rồi được xoá nếu bạn thấy ổn.", type: "dare", difficulty: "hard", rarity: "epic" },
            { id: "dare_032", text: "Làm MC phỏng vấn nhanh 3 người trong nhóm, mỗi người 1 câu.", type: "dare", difficulty: "hard", rarity: "rare" },
            { id: "dare_033", text: "Tỏ tình kịch tính với một đồ vật trong phòng.", type: "dare", difficulty: "insane", rarity: "legendary" },
            { id: "dare_034", text: "Diễn cảnh chia tay một chiếc ghế trong 20 giây.", type: "dare", difficulty: "insane", rarity: "epic" },
            { id: "dare_035", text: "Để nhóm chọn 5 động tác, bạn phải nối thành một bài nhảy 20 giây.", type: "dare", difficulty: "insane", rarity: "legendary" },
            { id: "dare_036", text: "Làm bài phát biểu cảm ơn cả nhóm như vừa nhận giải lớn.", type: "dare", difficulty: "insane", rarity: "epic" },
            { id: "dare_037", text: "Chọn 3 người và dựng một cảnh drama học đường 30 giây.", type: "dare", difficulty: "insane", rarity: "legendary" },
            { id: "dare_038", text: "Trong 1 lượt tiếp theo, mọi câu bạn nói phải có vần.", type: "dare", difficulty: "insane", rarity: "legendary" },
            { id: "dare_039", text: "Để cả nhóm đặt cho bạn một thử thách biểu cảm 15 giây.", type: "dare", difficulty: "insane", rarity: "epic" },
            { id: "dare_040", text: "Làm huấn luyện viên cổ vũ cả nhóm trong 20 giây.", type: "dare", difficulty: "insane", rarity: "legendary" }
        ],
        penalty: [
            { id: "penalty_001", text: "Uống một ly nước phạt.", type: "penalty", difficulty: "easy", rarity: "common" },
            { id: "penalty_002", text: "Đứng nghiêm chào cả nhóm.", type: "penalty", difficulty: "easy", rarity: "common" },
            { id: "penalty_003", text: "Nói 'tôi xin nhận phạt' thật dõng dạc.", type: "penalty", difficulty: "easy", rarity: "common" },
            { id: "penalty_004", text: "Đổi chỗ ngồi với người bên phải.", type: "penalty", difficulty: "easy", rarity: "common" },
            { id: "penalty_005", text: "Tự giới thiệu lại bản thân bằng giọng rất nghiêm túc.", type: "penalty", difficulty: "easy", rarity: "common" },
            { id: "penalty_006", text: "Làm biểu cảm đáng thương trong 5 giây.", type: "penalty", difficulty: "easy", rarity: "common" },
            { id: "penalty_007", text: "Hít đất 5 cái.", type: "penalty", difficulty: "easy", rarity: "common" },
            { id: "penalty_008", text: "Cúi chào 3 người gần nhất như gặp sếp.", type: "penalty", difficulty: "easy", rarity: "common" },
            { id: "penalty_009", text: "Nói 'tôi sai rồi' bằng 3 giọng khác nhau.", type: "penalty", difficulty: "medium", rarity: "common" },
            { id: "penalty_010", text: "Giữ mặt nghiêm trong khi cả nhóm chọc cười 20 giây.", type: "penalty", difficulty: "medium", rarity: "rare" },
            { id: "penalty_011", text: "Để nhóm đặt một hình phạt nhẹ trong 30 giây.", type: "penalty", difficulty: "medium", rarity: "rare" },
            { id: "penalty_012", text: "Nói lời xin lỗi với một đồ vật trong phòng.", type: "penalty", difficulty: "medium", rarity: "common" },
            { id: "penalty_013", text: "Khen 3 người bất kỳ, mỗi người một câu khác nhau.", type: "penalty", difficulty: "medium", rarity: "common" },
            { id: "penalty_014", text: "Đứng một chân trong 15 giây.", type: "penalty", difficulty: "medium", rarity: "rare" },
            { id: "penalty_015", text: "Nói chuyện bằng giọng MC trong 1 lượt tiếp theo.", type: "penalty", difficulty: "medium", rarity: "rare" },
            { id: "penalty_016", text: "Để người bên trái đặt cho bạn một biệt danh trong 1 lượt.", type: "penalty", difficulty: "medium", rarity: "common" },
            { id: "penalty_017", text: "Giữ tư thế plank 20 giây.", type: "penalty", difficulty: "hard", rarity: "rare" },
            { id: "penalty_018", text: "Hát quốc ca bằng giọng cực kỳ nghiêm trọng.", type: "penalty", difficulty: "hard", rarity: "epic" },
            { id: "penalty_019", text: "Để một người vẽ ký hiệu nhỏ lên tay bạn.", type: "penalty", difficulty: "hard", rarity: "epic" },
            { id: "penalty_020", text: "Làm MC giới thiệu 5 người trong nhóm như siêu sao.", type: "penalty", difficulty: "hard", rarity: "rare" },
            { id: "penalty_021", text: "Trong 2 lượt tiếp theo, mỗi lần nói phải bắt đầu bằng 'theo tôi nghĩ'.", type: "penalty", difficulty: "hard", rarity: "epic" },
            { id: "penalty_022", text: "Để nhóm chọn một dáng đứng, giữ dáng đó 10 giây.", type: "penalty", difficulty: "hard", rarity: "rare" },
            { id: "penalty_023", text: "Xin chữ ký 3 người như fan gặp thần tượng.", type: "penalty", difficulty: "hard", rarity: "epic" },
            { id: "penalty_024", text: "Đọc tên 8 người trong nhóm thật nhanh, sai thì đọc lại.", type: "penalty", difficulty: "hard", rarity: "rare" },
            { id: "penalty_025", text: "Trong 2 lượt tiếp theo, chỉ được nói như nhân vật phản diện.", type: "penalty", difficulty: "insane", rarity: "legendary" },
            { id: "penalty_026", text: "Xin chữ ký từng người như fan cuồng và cảm ơn thật sâu sắc.", type: "penalty", difficulty: "insane", rarity: "legendary" },
            { id: "penalty_027", text: "Làm bài phát biểu xin lỗi cả nhóm trong 30 giây.", type: "penalty", difficulty: "insane", rarity: "epic" },
            { id: "penalty_028", text: "Để nhóm chọn một từ, bạn phải nhắc từ đó 5 lần trong một câu hợp lý.", type: "penalty", difficulty: "insane", rarity: "epic" },
            { id: "penalty_029", text: "Diễn cảnh bị phạt oan trong 20 giây.", type: "penalty", difficulty: "insane", rarity: "legendary" },
            { id: "penalty_030", text: "Tự đặt khẩu hiệu cho bản thân và hô 3 lần như đội cổ vũ.", type: "penalty", difficulty: "insane", rarity: "legendary" }
        ]
    };;
})();
